version: '3'

services:
  ghost:
    image: ghost:5.40.2
    restart: always
    ports:
      - 2368:2368
    volumes:
      - ghost_data:/var/lib/ghost/content
    environment:
      - database__client=sqlite3
      - database__connection__filename=/var/lib/ghost/content/data/ghost-local.db
volumes:
  ghost_data: